Bug#34186909 MySQL cluster does not build on 32 bit platform
Build with any bitness, warn if not 64 bit.

Fix failing unittest cstrbuf-t due to different size of pointers causing
sizeof checks to fail.

Add implicit padding in ndbxfrm1::header caused static assertion
failure:

storage/ndb/src/common/util/ndb_ndbxfrm1.cpp: In member function 'int ndb_ndbxfrm1::header::fixed_header::toggle_endian()':
storage/ndb/src/common/util/ndb_ndbxfrm1.cpp:1030:60: error: static assertion failed: Remember update ndb_ndbxfrm1::header::fixed_header::toggle_endian() when adding new fields.
   static_assert(sizeof(ndb_ndbxfrm1::header::fixed_header) == 160,
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~

Fix compiler warnings:

storage/ndb/src/common/util/ndbxfrm_file.cpp: In member function 'int ndbxfrm_file::read_forward(ndbxfrm_output_iterator*)':
storage/ndb/src/common/util/ndbxfrm_file.cpp:1254:31: error: comparison of integer expressions of different signedness: 'off_t' {aka 'long long int'} and 'uintmax_t' {aka 'long long unsigned int'} [-Werror=sign-compare]
         if (m_file_pos + size > (uintmax_t)m_payload_end)
             ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~

storage/ndb/src/common/util/ndbxfrm_file.cpp: In member function 'int ndbxfrm_file::read_backward(ndbxfrm_output_reverse_iterator*)':
storage/ndb/src/common/util/ndbxfrm_file.cpp:1421:35: error: comparison of integer expressions of different signedness: 'uintmax_t' {aka 'long long unsigned int'} and 'off_t' {aka 'long long int'} [-Werror=sign-compare]
         if ((uintmax_t)m_file_pos < m_payload_start + size)
             ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~

storage/ndb/src/ndbapi/TransporterFacade.cpp: In member function 'bool TransporterFacade::configure(NodeId, const ndb_mgm_configuration*)':
storage/ndb/src/ndbapi/TransporterFacade.cpp:1841:11: error: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'size_t' {aka 'unsigned int'} [-Werror=format=]
           "Unable to allocate %lu bytes of memory for send buffers!!",
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           total_send_buffer_size_t);
           ~~~~~~~~~~~~~~~~~~~~~~~~

In file included from storage/ndb/src/kernel/blocks/dblqh/Dblqh.hpp:28,
                 from storage/ndb/src/kernel/blocks/dbtup/DbtupExecQuery.cpp:27:
storage/ndb/src/kernel/blocks/dbtup/DbtupExecQuery.cpp: In member function 'Uint32 Dbtup::copyAttrinfo(Uint32, bool)':
storage/ndb/src/kernel/blocks/dbtup/DbtupExecQuery.cpp:186:27: error: comparison of integer expressions of different signedness: 'const Uint32' {aka 'const unsigned int'} and 'int' [-Werror=sign-compare]
       ndbassert(readerLen == (pos - cinBuffer));
                 ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
storage/ndb/src/kernel/vm/pc.hpp:295:13: note: in definition of macro 'ndbassert'
   if(likely(check)){ \
             ^~~~~

Change-Id: I7900b724bd9485f0545a276face9d774d2c92bfd