Bug#34428430 Router doesn't reply to Mysqlx::Connection::Close message
Post-push fix for older protoc versions:
router/tests/component/test_routing.cc:1841:31: error:
no member named 'ArrayOutputStream' in namespace 'google::protobuf::io';

Change-Id: I46d82c46ecf5e4339363f01a5738e16572a9162d
(cherry picked from commit c4cd57dbb23950505b79224a8841e72c0463c544)