Bug#22680706: 5.5 DOES NOT BUILD WITH GCC5
Fix the following two build warnings so that 5.5 can be compiled
with GCC5.

storage/innobase/dict/dict0crea.c:1143:21: error: logical not is only applied
to the left hand side of comparison [-Werror=logical-not-parentheses]
   ut_a(!node->index == (err != DB_SUCCESS));
                     ^
storage/innobase/log/log0recv.c:1770:20: error: logical not is only applied
to the left hand side of comparison [-Werror=logical-not-parentheses]
  ut_ad(!allow_ibuf == mutex_own(&log_sys->mutex));
                    ^