Bug#35781622 Switch from -std=c++17 to -std=c++20
Post-push fix: -Wambiguous-reversed-operator

Clang 16 on windows says:
src\user_map.cc(186,35):
error: ISO C++20 considers use of overloaded operator '=='
(with operand types 'Sid' and 'Sid')
to be ambiguous despite there being a unique best viable function
[-Werror,-Wambiguous-reversed-operator]
    if (p->m_sid.is_user() && who == p->m_sid) {
                              ~~~ ^  ~~~~~~~~

Change-Id: Ib0fe9c739b6466763ec617890e9320b7c211c44a