Bug#32877703: REWRITE JSON_LENGTH(DOC, PATH) TO JSON_LENGTH(JSON_EXTRACT(DOC, PATH))
JSON_LENGTH takes an optional second argument, which is the path to
the element to get the length of. If the second argument is not given,
the length of the top-level JSON document is returned.

This patch rewrites the two-argument form of JSON_LENGTH to the
single-argument form of JSON_LENGTH by adding an intermediate call to
JSON_EXTRACT. That is, JSON_LENGTH(doc, path) is rewritten to
JSON_LENGTH(JSON_EXTRACT(doc, path)) during parsing. This simplifies
the implementation of JSON_LENGTH.

This rewriting does not change the result of any calls to JSON_LENGTH
that returned without an error before the change. It does however
change how JSON_LENGTH behaves when the path argument contains a
wildcard, an ellipsis or an array range. Before, it would raise an
error if such a path is given. Now, it returns the number of elements
matching that path.

Before the patch:

mysql> SELECT JSON_LENGTH('[1,2,3,4,5,6,7]', '$[2 to 4]') AS x;
ERROR: 3149 (42000): In this situation, path expressions may not contain the * and ** tokens or an array range.

After the patch:

mysql> SELECT JSON_LENGTH('[1,2,3,4,5,6,7]', '$[2 to 4]') AS x;
+---+
| x |
+---+
| 3 |
+---+

Since the only difference is that JSON_LENGTH now returns without an
error in more cases than before, this change is not expected to cause
problems for existing callers.

Change-Id: I33e16f9ae413237963b95caa373da5b274f6221e