Bug#23212938 ADD SUPPORT FOR SOLARIS STUDIO 12.5 AKA 5.14
Extra patch for mysql-trunk.

================
include/decimal.h
sql/my_decimal.h
strings/decimal.cc

query 'connect plug_con,localhost,plug,plug_dest' failed: 2059:
Authentication plugin 'auth_test_plugin' cannot be loaded:
ld.so.1: mysqltest: fatal: relocation error: file
plugin/auth/auth_test_plugin.so: symbol internal_str2dec:
referenced symbol not found

The problem was this 'extern "C"' function
static inline int string2decimal(const char *from,
                                 decimal_t *to,
                                 char **end)
{
  return internal_str2dec(from, to, end, FALSE);
}

The Solaris Studio C compiler left an unresolved reference to internal_str2dec
even if the function was un-used.

Fix: either rewrite all plugins to be C++ (remove 'static' which
enables C++ weak references), or the chosen solution:
Remove the code from include/decimal.h, it is not used by any C source code.

================
include/my_sys.h
rapid/plugin/x/ngs/src/thread.cc

t@30 (l@30) terminated by signal SEGV (subcode 32767)
0xffffffff7f3e1f14: _stack_grow+0x0048: ldub     [%o1 - 1], %g0
Current function is MYSQLparse
19775   YYSTYPE yylval YY_INITIAL_VALUE(yyval_default);
current thread: t@30
  [1] _stack_grow(0xffffffff7f54c341, 0xffffffff7f550000, 0x40000, 0xffffffff7f54f801, 0xe860, 0x104480e40), at 0xffffffff7f3e1f14
=>[2] MYSQLparse(YYTHD = 0xffffffff7f566448), line 19775 in "sql_yacc.cc"
  [3] parse_sql(thd = 0x13edabb08, parser_state = 0xffffffff7f55ed40, creation_ctx = 0x13ee59410), line 7049 in "sql_parse.cc"

The problem was that threads created by/for the X plugin had a much
smaller actuall stack size than my_thread_stack_size, thus making
check_stack_overrun() defunct.

Fix: use my_thread_stack_size when creating threads which will execute
SQL in the server.

================
rapid/plugin/x/mysqlxtest_src/mysqlx.cc
rapid/plugin/x/ngs/src/client.cc

program terminated by signal BUS (invalid address alignment)
Current function is mysqlx::Connection::send
  663     *buf_ptr = msg.ByteSize() + 1;
=>[1] mysqlx::Connection::send(this = 0x100de5240, mid = 4, msg = CLASS), line 663 in "mysqlx.cc"

Fix: move byte-buffer into anonymous union, to ensure alignment.

================
sql/json_dom.cc
sql/json_dom.h"

Error: Attempt to initialize multiple variant members in
'Json_wrapper' by initializing 'm_dom_alias'.

Fix: Initialize m_dom_alias in CTOR body rather than CTOR init list.

================
storage/innobase/CMakeLists.txt

Linking CXX executable mysqld
Undefined                    first referenced
 symbol                             in file
boost::atomics::detail::lockpool::scoped_lock::scoped_lock(volatile const void*)
 ../storage/innobase/libinnobase.a(buf0buf.cc.o)

Problem was that Solaris Studio generates dependencies on
boost::atomics::detail::lockpool::scoped_lock::scoped_lock

Fix: add libs/atomic/src/lockpool.cpp to list of source files for InnoDB