WL#7440 : Fixing Linker errors on Windows-32bit OS
  Problem:  
  ========  
  The library libbinlogevents uses stream classes in the standard input/output
  library, which are not linked to mysqld, when compiled on windows-32 bit
  systems, with the following error: 

   error LNK2001: unresolved external symbol _CTA4?AVfailure@ios_base@std@@  

  Fix: 
  ====
  Since the methods provided by standard ios are used only in the free standing
  version of the library, we exclude the code using preprocessor symbol 
  HAVE_MYSYS, when built with the server.