Bug#34199675 Dbtup compiler warning for nullptr subtraction
Problem:
storage/ndb/src/kernel/blocks/dbtup/DbtupFixAlloc.cpp:167:37: error:
'this' pointer is null [-Werror=nonnull]
  167 |     gci_pos = Uint32(ptr->get_mm_gci(regTabPtr) - (Uint32*)ptr);
      |                      ~~~~~~~~~~~~~~~^~~~~~~~~~~

Solution:
Rewrite to use a function that returns position of the "mm_gci" wihtout
using nullptr subtraction.

Change-Id: I04382c6aa2692642225db2ef94205605dfe4cea4