Bug#28380808 NDB : GRACEFUL STOP API STATE NOTIFICATION TOO SLOW
Post push fix for fatal compiler warning with gcc 8.0.1:
  QmgrMain.cpp:8001:60: error: type qualifiers ignored on cast result
type [-Werror=ignored-qualifiers]
       (const NodeInfo::NodeType) getNodeInfo(nodeToNotify).m_type;
                                                            ^~~~~~

Fix by using NodeInfo accessor function which returns NodeInfo::NodeType
instead of direct accessing of member variable of type Uint32 using
unneccessary cast.

Change-Id: I5234335e69291e22b6e6a801af57d67c4a6ffddd