- Adding documentation for User_var_event and Rand_event - Changed the name of method get_version_product to get_product_version as it make more sense that way. - Fixing the Solaris compiliation failure
  Error: In the switch case inside ctor 
         Format_description_event(uint8_t binlog_ver, const char* server_ver)
         we are getting the error "case bypass initialization of local variable"
  
  Fix:   case 3: should be surrounded by braces as we are defining a local
         variable server_event_header_length_ver_1_3 there.
         When you have a variable in a case, the variable exists in cases
         below it but the variable won't exist because the code that 
         initialized it got skipped by the case statement

- Addressed reveiw comments