BUG#33119775 BUILD BREAK WITH LOCK_ORDER IN SQL_TABLE.CC
This fix is to address a build break.

Before this fix, compiling with WITH_LOCK_ORDER in CMake
caused the following failure:

[ 30%] Building CXX object sql/CMakeFiles/sql_main.dir/sql_table.cc.o
/home/malff/CODE/GIT/GIT_TRUNK/sql/sql_table.cc: In function ‘bool mysql_rename_table(THD*, handlerton*, const char*, const char*, const char*, const char*, const dd::Schema&, const char*, const char*, uint)’:
/home/malff/CODE/GIT/GIT_TRUNK/sql/sql_table.cc:10456:18: error: ‘drop_table_share’ was not declared in this scope
   PSI_TABLE_CALL(drop_table_share)
                  ^~~~~~~~~~~~~~~~

The root cause is a regression introduced by:

commit f34f9c02e560002730a1eb11c6c092ddffb176fd
Author: Knut Anders Hatlen <knut.hatlen@oracle.com>
Date:   Tue Jul 6 15:42:06 2021 +0200

    Bug#32983024: USE A DIFFERENT HASH FUNCTION FOR GENERATED HIDDEN COLUMN NAMES

which removed the following includes in file sql/sql_table.cc:
  -#include "mysql/psi/mysql_table.h"
  -#include "mysql/psi/psi_table.h"

This removal is mostly likely caused by clang-format,
which missed the fact that these headers are needed in some configurations,
like WITH_LOCK_ORDER.

The fix is to add these includes again,
and mark them with special "IWYU pragma: keep" directives,
to instruct clang-format to preserve the code when re formatting.

Approved by: Chris Powers <chris.powers@oracle.com>