BUG#20429800 INNODB: UNDEFINED REFERENCE TO MY_CHARSET_GBK_CHINESE_CI IN FTS_IS_CHARSET_CJK
Analysis: my_charset_gbk_chinese_ci is not define when mysql is compiled
with -DWITH_EXTRA_CHARSETS=none.

Solution: compare charset name instead of charset pointer.

Reviewed-by: Jimmy Yang <jimmy.yang@oracle.com>