BUG#33646899: MTS + STOP SLAVE SQL_THREAD + group of rep events stops  before 60 sec timeout
 Description:
 ------------
 Issuing STOP SLAVE SQL_THREAD command while sql thread is handling
 a transaction that interacts with non-transaction table caused
 below error:

 2022-08-03T18:01:11.995956Z 122 [Warning] Slave SQL for channel '':
 Request to stop slave SQL Thread received while applying a group that
 has non-transactional changes; waiting for completion of the group
 ... , Error_code: 0
 2022-08-03T18:01:13.015261Z 124 [ERROR] Slave SQL for channel '':
 Fatal error: ... Slave SQL Thread stopped with incomplete event
 group having non-transactional changes. If the group consists
 solely of row-based events, you can try to restart the slave with
 --slave-exec-mode=IDEMPOTENT, which ignores duplicate key, key not
 found, and similar errors (see documentation for details).
 Error_code: 1593

 The replica was supposed to wait 60 seconds(SLAVE_WAIT_GROUP_DONE
 timeout) to wait for the group of events to complete and then force
 the stop of the SQL thread. However the timestamps indicate it
 did not wait a second before it threw the error and stopped
 replication.

 Analysis:
 ------------
 The issue is due to the variable(last_event_start_time) which keeps
 last event start time(last_event_start_time) is not getting resetted
 after sql thread restart. When the variable is not reset, and the
 thread is started again, and then stopped a second time, the second
 'stop' will not set a new value from the variable. So it will use
 the same timeout as the preceding 'stop slave', i.e., force-stop
 workers when 60 seconds have elapsed after the *first* stop slave
 statement.The Issue occurs only when running replication in single
 thread mode.

 Fix:
 ----
 Reset last_event_start_time at the start of sql thread.

Change-Id: I3614e89a2d121696970e19f138088567ed068091