WL#10310 Redo log optimization: dedicated threads and concurrent log buffer.
Post-push fix for clang warnings:

storage/innobase/include/sync0sharded_rw.h:61:24: error: lambda capture
      'latch_level' is not used [-Werror,-Wunused-lambda-capture]
    for_each([pfs_key, latch_level](rw_lock_t &lock) {

unittest/gunit/innodb/log0log-t.cc:482:8: error: lambda capture
      'max_dirty_page_age' is not required to be captured for this use [-Werror,-Wunused-lambda-capture]
      [max_dirty_page_age](size_t thread_no) {

Change-Id: I94e89cf47101fd0d2224a1f0b1c41b5b0c0eae3f