WL#15839: Remove default_authentication_plugin variable
Post-push fix for broken clang -Werror build:

unittest/gunit/authentication_policy-t.cc:67:11: error:
parameter 'factor:' not found in the function declaration
[-Werror,-Wdocumentation]
   @param factor: the factor

Change-Id: I482bfc14239d7f49ab4fef66b8b387b9c82bf7ee
(cherry picked from commit f1517adddfeaa3dc36f54cc55e99f241748418a0)