Followup to vasil.dimov@oracle.com-20140409172641-jf52d93p1f1yo1x1:
Add an explicit typecast, needed to fix a Windows 32 only compilation error:

...\os0once.h(89): error C2664: '_InterlockedCompareExchange' : cannot convert parameter 1 from 'volatile os_once::state_t *' to 'volatile long *'
Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast