Bug #30474056 MYSQL FAILED TO BUILD DUE TO ERROR C2039 WITH MSVC ON WINDOWS
Boost feature check may fail on windows.
Compiler bug was fixed in VC++ 2013, workaround no longer necessary.

The patch copies two boost headers, and patches them, to fix a feature
detection which is obsolete. We expect the problem to be fixed
upstream at some point in the future.

Essentially the same patch for both files:
  <     #if BOOST_WORKAROUND(BOOST_MSVC, BOOST_TESTED_AT(1700))
  ---
  >     #if BOOST_WORKAROUND(BOOST_MSVC, < 1800)

Change-Id: I1d3f54bde83d747de320cd4cc678c1ba6f431bee