Bug#18790490: NOISY COMPILER WARNINGS ON FREEBSD 10
Fix the following two header file compile warnings by backporting
changes from mysql-trunk:
/usr/include/sys/timeb.h:42:2: error: "this file includes <sys/timeb.h> which is deprecated"
dict0dict.h:85:1: error: attribute declaration must precede definition