Bug#32933085 routertest_harness_std_monitor fails on windows
Issue
=====

routertest_harness_stdx_monitor sometimes fails on windows with:

----------] 1 test from WaitableMonitor
[ RUN      ] WaitableMonitor.move_only
router\harness\tests\test_stdx_monitor.cc(79):
error: Expected equality of these values:
  1
  m([](const auto &v) { return v.value(); })
    Which is: 0
[  FAILED  ] WaitableMonitor.move_only (124 ms)
[----------] 1 test from WaitableMonitor (124 ms total)

Change
======

- wait 30s instead of 100ms
- EXPECT that wait_for() doesn't timeout
- added more tests

RB: 26480