WL#15123: User defined histograms
Post-push fix for warning from clang:

histogram.cc:269:3: error: '~Histogram_error_handler' overrides a
destructor but is not marked 'override'
[-Werror,-Winconsistent-missing-destructor-override]

Change-Id: Iab9248b947a808f2567acc306a6b31e37c1987a3