Bug#36775910: Record buffer not set in index range scans
Post-push fix for broken build: sql_executor.cc:767:21: error:
declaration of 'max_rows' shadows a previous local [-Werror=shadow=compatible-local]

Change-Id: Ia09e96d083326773270b5aadde75f519b095e8f2
(cherry picked from commit a61fca5f7eb5ef1c323f814f4f9365d17985ded4)