Bug #30338980 REMOVE THE C MACROS SET_IF_BIGGER AND SET_IF_SMALLER
Remove C macros set_if_bigger and set_if_smaller.
Use standard C++ constructs instead.

set_if_bigger(a,b) => a = std::max(a,b)
set_if_smaller(a,b) => a = std::min(a,b)

One extra change isnan() => std::isnan() because gcc 5.4 complained:
storage/heap/hp_hash.cc:571:21: error: 'isnan' was not declared in this scope

Change-Id: I41ce098c295c218b097378cad57932b3cb868b5d