Bug#35855573 Assertion `false && "Inconsistent row counts for different AccessPath objects."' [1/2]
Post-push fix:
join_optimizer/join_optimizer.cc:6748:15: error:
unused variable 'join' [-Werror,-Wunused-variable]

Change-Id: I66f8f5865ddf8cbc741fe576ea7600dfa58ece77