Fix operator name keywords causing incompatibility with -fno-operator-names
Alternative operator name keywords like `and`, `or`, `xor`, etc., are
rarely used in MySQL and can cause obscure errors when the GCC flag
`-fno-operator-names` is applied, for example:

```
/MySQL/storage/temptable/include/temptable/lock_free_type.h:125:75: error: template argument 2 is invalid
  125 |                                std::is_trivially_copyable<T>::value>::type> {
      |                                                                           ^
/MySQL/storage/temptable/include/temptable/lock_free_type.h:148:19: error: parse error in template argument list
  148 |     typename std::enable_if<std::is_same<T, long long>::value or
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  149 |                             std::is_same<T, unsigned long long>::value>::type> {
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Replace the few occurrences of operator name keywords to use their
primary counter parts, like `&&`, `||`, and `!`.