Bug#36108397 Upgrade to latest protobuf library [patches]
Local patches:

In several of our own cmake sources:
   TARGET_COMPILE_FEATURES(${TARGET} PUBLIC cxx_std_20)
This will override any cxx_std_14 or cxx_std_17 properties set on
libraries we link in from abseil or protobuf.
Those PUBLIC properties on 3rd party libs broke the build on Mac.

CMakeLists.txt
  For "bundled" protobuf, we need "bundled" abseil also.

  Silence -Wstringop-overflow warnings in libraries generated
  from.proto files.

cmake/protobuf_proto_compile.cmake
  Abseil header file directories must be part of the public interface
  for libraries generated from .proto files.

extra/abseil/abseil-cpp-20230802.1/absl/base/CMakeLists.txt
  Rename cmake variable LIBRT, to avoid name conflicts with our own
  cmake code.

extra/protobuf/CMakeLists.txt
  Silence more warnings.
  Build static protobuf libraries also on Windows.
  TODO: build shared protobuf and abseil libs, and INSTALL them.

extra/protobuf/protobuf-24.4/CMakeLists.txt
  Disable INSTALL and BUILD_TESTS.

extra/protobuf/protobuf-24.4/cmake/libprotobuf-lite.cmake
extra/protobuf/protobuf-24.4/cmake/libprotobuf.cmake
extra/protobuf/protobuf-24.4/cmake/libprotoc.cmake
  Disable the --version-script which is bundled with protobuf sources,
  we need to apply our own version script instead.
  Add our own INSTALL targets for shared libraries.

extra/protobuf/protobuf-24.4/cmake/protobuf-configure-target.cmake
  disable the /MP compiler option for clang on Windows

Misc. CMakeLists.txt files
  Disable -DPROTOBUF_USE_DLLS.
  TODO: build shared proto and absl libs on Windows.

opentelemetry-cpp/opentelemetry-cpp-1.10.0/CMakeLists.txt
  Rename the WITH_ABSEIL cmake option (previously default to OFF) to
  TELEMETRY_WITH_ABSEIL (default ON) so that the build is not
  broken after a 'git pull'.

opentelemetry-cpp/opentelemetry-cpp-1.10.0/api/CMakeLists.txt
  Disable find_package(absl) for "bundled" protobuf/abseil.

storage/innobase/handler/i_s.cc
  Misc gcc versions started to complain about:
  storage/innobase/handler/i_s.cc:722:5: error:
  either all initializer clauses should be designated or none of them should be
    722 |     nullptr,

Change-Id: I2dcec2a3f489d180015b3feeeef966f0bc3af676