Bug#36040942 router build on 32bit linux fails
On Linux 32bit, make all fails with:

router/src/harness/tests/linux_timestamping.cc:156:5: error: missing
binary operator before token "("
  156 | #if SO_TIMESTAMP == SO_TIMESTAMP_NEW
      |     ^~~~~~~~~~~~

That's caused by SO_TIMESTAMP being defined as:

  #define SO_TIMESTAMP (sizeof(time_t) == sizeof(__kernel_long_t) ?
  SO_TIMESTAMP_OLD : SO_TIMESTAMP_NEW)

(in /usr/include/asm-generic/socket.h). But ?: isn't allowed in an
"#if".

Change
======

- use std::conditional_t<> instead of ifdef to select the right type.

Change-Id: I3243812ab04eae509baeec259572e42a03aa36d1