Bug#35826429 - Compilation issue in connection_manager.cc
Description
===========
Compiling MySQL Server with "-DMYSQL_MAINTAINER_MODE=ON" and "-DENABLE_GCOV=ON",
causes a compilation error at: plugin/x/tests/driver/connector/connection_manager.cc:326

    void* __builtin_memset(void*, int, long unsigned int)
    // specified size 18446744073709551614 exceeds maximum object size 9223372036854775807

triggered by following call:

    if (!slist.empty()) slist.resize(slist.length() - 2);

Fix
===
Changed the source code, in a way that "gcc" doesn't trigger a warning (false negative).

Change-Id: I4c2b9bc12483412e1f66f6b0a46ea29221f3130b