WL#12637 Step 1: Refactor ACL change notification to engines
Post-push fix for broken build
sql/auth/sql_user_table.cc:562:10: error:
unused parameter 'thd' [-Werror,-Wunused-parameter]

Change-Id: If7e9626a10cde685cd6b013ee0ecef8c65c494dd