Bug#30883833 : INPLACE ENCRYPTION RESUME THREAD DOESN'T UPDATE DD PROPERLY
Post-push fix:
storage/innobase/fsp/fsp0fsp.cc:4525:13: error:
      unused variable 'err' [-Werror,-Wunused-variable]

Change-Id: Ifaaaac453a2906d237f3b3c68f93fe3913c02b15