Bug#35658072 management nodes are unable to allocate node id to data and sql pods when restarted
Post push fix for compilation error due to unaligned doxygen comments.

storage/ndb/src/mgmsrv/MgmtSrvr.cpp:3618:11: error: parameter 'nodes'
not found in the function declaration [-Werror,-Wdocumentation]
   @param nodes Output list of nodes matching client address
          ^~~~~
storage/ndb/src/mgmsrv/MgmtSrvr.cpp:3618:11: note: did you mean
'node_matches'?
   @param nodes Output list of nodes matching client address
          ^~~~~
          node_matches

Change-Id: Id5fecd67a3a064f8f5051b879119fa66540b0b2e