Fix compilation errors:
Error 1:
--------
[ 38%] Building CXX object storage/innobase/CMakeFiles/innobase.dir/api/api0api.cc.o
In file included from /home/vdimov/bzrroot/server/mysql-trunk/storage/innobase/api/api0api.cc:27:
/home/vdimov/bzrroot/server/mysql-trunk/storage/innobase/include/ha_prototypes.h:132: error: use of enum 'durability_properties' without previous declaration
/home/vdimov/bzrroot/server/mysql-trunk/storage/innobase/include/ha_prototypes.h:136: error: invalid type in declaration before ';' token
In file included from /home/vdimov/bzrroot/server/mysql-trunk/storage/innobase/include/rem0cmp.h:205,
                 from /home/vdimov/bzrroot/server/mysql-trunk/storage/innobase/include/page0page.ic:32,
                 from /home/vdimov/bzrroot/server/mysql-trunk/storage/innobase/include/page0page.h:1125,
                 from /home/vdimov/bzrroot/server/mysql-trunk/storage/innobase/include/page0cur.h:32,
                 from /home/vdimov/bzrroot/server/mysql-trunk/storage/innobase/include/btr0pcur.h:33,
                 from /home/vdimov/bzrroot/server/mysql-trunk/storage/innobase/api/api0api.cc:33:
/home/vdimov/bzrroot/server/mysql-trunk/storage/innobase/include/rem0cmp.ic: In function 'int cmp_dfield_dfield_like_prefix(const dfield_t*, const dfield_t*)':

REASON: ha_prototypes.h uses durability_properties, which is defined in
sql_class.h, but ha_prototypes.h does NOT #include sql_class.h.
SOLUTION: #include sql_class.h in ha_prototypes.h in order to get the
definition of durability_properties.

Error 2 (after fixing the above erorr(s)):
------------------------------------------
[ 42%] Building CXX object storage/innobase/CMakeFiles/innobase.dir/fts/fts0blex.cc.o
In file included from fts0blex.l:28:
/home/vdimov/bzrroot/server/mysql-trunk/storage/innobase/include/fts0ast.h:272: error: ISO C++ forbids declaration of 'CHARSET_INFO' with no type
/home/vdimov/bzrroot/server/mysql-trunk/storage/innobase/include/fts0ast.h:272: error: expected ';' before '*' token
make[2]: *** [storage/innobase/CMakeFiles/innobase.dir/fts/fts0blex.cc.o] Error 1
make[1]: *** [storage/innobase/CMakeFiles/innobase.dir/all] Error 2
make: *** [all] Error 2

REASON: fts0ast.h uses CHARSET_INFO, which is defined in
ha_prototypes.h, but fts0ast.h does NOT #include ha_prototypes.h.
SOLUTION: #include ha_prototypes.h in fts0ast.h in order to get the
definition of CHARSET_INFO.

Error 3 (after fixing the above erorr(s)):
------------------------------------------
[ 69%] Building CXX object extra/CMakeFiles/innochecksum.dir/__/storage/innobase/ut/ut0crc32.cc.o
/home/vdimov/bzrroot/server/mysql-trunk/storage/innobase/ut/ut0crc32.cc: In function 'void ut_cpuid(ib_uint32_t*, ib_uint32_t*, ib_uint32_t*, ib_uint32_t*, ib_uint32_t*, ib_uint32_t*)':
/home/vdimov/bzrroot/server/mysql-trunk/storage/innobase/ut/ut0crc32.cc:152: error: 'memcmp' was not declared in this scope
make[2]: *** [extra/CMakeFiles/innochecksum.dir/__/storage/innobase/ut/ut0crc32.cc.o] Error 1
make[1]: *** [extra/CMakeFiles/innochecksum.dir/all] Error 2
make: *** [all] Error 2

REASON: ut0crc32.cc uses memcmp(), which is defined in
string.h, but ut0crc32.cc does NOT #include string.h.
SOLUTION: #include string.h in ut0crc32.cc in order to get the
definition of memcmp().