Bug#34853213 Angel data node does not detect if child data node exits normally
Description:

On Windows angel data node does not detect if child data node exits
normally.

When running MTR tests on Windows, tests succeed but when MTR sometimes
need to stop all processes the angel data node linger and need to be
forcefully killed, this is visible by the non fatal error messages like:

    ERROR: A process did not stop gracefully, killing it forcefully. If this happens, a child process seems to have a bug. [cmdline = "C:/.../ndbmtd.exe --defaults-file=R:/var-ndb/1/my.cnf --defaults-group-suffix=.1.1 --nodaemon"]. at lib/My/SafeProcess.pm line 261, <GEN8> line 23.

The angel periodically poll for child exit status using the process id.

On POSIX system that works since a child process will by default linger
as zombie process with the same process id until parent has waited for
it to get the exit status (or ignoring SIGCHLD).

On Windows there is no such guarantee that process id will be valid and
refer to child after child process have stopped.
Rather parent should keep an open process handle to child and use that
and polling for exit status.

When child data node is stopped in tests to be restarted the angel do
detect that. It seems to be due to that child has written to the
angel-child pipe before it exits, which angel will read from after it
seen child die.

How To Repeat:

Build cluster on Windows and run MTR, look for printouts "ERROR: A
process did not stop gracefully, killing it forcefully."

Fix:

A class process_waiter is introduced providing a wait function that on
Windows keep an open process handle to child and use that when probing
for child exit. On non Windows waitpid is used as today.

Using process handle on Windows also affects code killing child, and
that functions is also implemented in process_waiter.

Change-Id: I6a56e851d4f6f67feb63a9d91053df735ba5906b