Bug #33574176 Compile MySQL with GCC 12
Build failed on Ubuntu 22.10 with gcc12
export LDFLAGS="-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro"

lto-wrapper: fatal error: make returned 2 exit status
Fix -Werror=maybe-uninitialized when building
libmysqlrouter_http.so.1

sql/ssl_wrapper_service.cc:73:10: error:
__builtin_strncpy specified bound 256 equals destination size
[-Werror=stringop-truncation]
   73 |   strncpy(buffer, ssl_version, buffer_size);

storage/ndb/plugin/ndb_stored_grants.cc:722:17:
str_start may be used uninitialized [-Wmaybe-uninitialized]
note: str_start was declared here
  722 |     const char *str_start;

when building mysqlbinlog:
include/my_time.h:200:19: error:
__builtin_strncpy specified bound depends on the length of the source argument
[-Werror=stringop-truncation]

silence -Werror=alloc-size-larger-than in
unittest/gunit/innodb/sync0rw-t.cc

unittest/gunit/regexp_engine-t.cc:136
/usr/include/c++/12/bits/char_traits.h:813:35: error:
__builtin_memmove reading 3 or more bytes from a region of size 2
[-Werror=stringop-overread]

router/src/routing/src/sql_lexer.cc
utf_txt.str may be used uninitialized [-Werror=maybe-uninitialized]

Also downgrade -Werror=maybe-uninitialized to a warning when linking
mysqld or server_unittest_library with lto.

Change-Id: Idbacc1cc1e76edabed44835927af2c69a09e471a
(cherry picked from commit 6a37c8f89ce0d384cf79aa29e056ee9427f6a08f)