WL#8726
  - compiler error detected with -Werror=logical-op in the assert
    which intend to cause a crash if the invalid setting occurs in
    a debug compile.

  storage/ndb/memcache/src/schedulers/S_sched.cc:189: error: logical
   'or' of collectively exhaustive tests is always
   true [-Werror=logical-op]
     assert(options.force_send >= 0 || options.force_send <= 2);
                                    ^

 - fix by changing the or to an and so it matches the condition
   which causes this code path to occur.
 - could just as well be changed to "assert(false)" avoiding
   duplicated but reversed code logic.

(cherry picked from commit a1809b9fe45facb9b567340d9a72bf4726061760)