Post push fix: Resolving build errors on Windows
Description:
  Error: error C2378: 'uint64_t' : redefinition;
         symbol cannot be overloaded with a typedef 
  
  Cause: definition of le64toh is interpreted as a definition of uint64_t
         in byteorder.h by the compiler.

  Fix: - Added checks to define uint64_t if stdint.h is not present on the
         platform
       - Added checks, so that the defintion of le64toh() is excluded if it is
       already present in the platform specific file, endian.h