WL#9053: Group Replication: Push Group Replication Plugin to mysql-trunk
Build with gcc (GCC) 5.4.0
error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
 #define number_is_valid_port(n) ((n) > 0 && (n) <= UINT16_MAX)

Fix: cast UINT16_MAX to int
(cherry picked from commit 940e828bb8213624aea163d45ada65871c15ea12)