Bug#26495816 CONTRIBUTION: INCLUDE MY_DIR.H
In 5.7 when building with -DWITHOUT_SERVER=1

my_symlink.c: In function my_is_same_file:
my_symlink.c:200:3: error: unknown type name MY_STAT

Regression introduced by:

BUG#25451091:CREATE TABLE DATA DIRECTORY / INDEX DIRECTORY

Fix: #include "my_dir.h"