Bug #30000085 ITEM_GEOFUNC_RELCHECKS_BGWRAP -WERROR=MAYBE-UNINITIALIZED]
Switch off -Werror=maybe-uninitialized for gcc 8.2 for this:

sql/item_geofunc_relchecks_bgwrap.cc:
In static member function
static int BG_wrap<Geom_types>::multipoint_disjoint_multi_geometry(const Multipoint&, const Geom_type&) [with Geom_type = Gis_multi_polygon; Geom_types = BG_models<boost::geometry::cs::cartesian>]:
sql/item_geofunc_relchecks_bgwrap.cc:496:44: error: *((void*)& box +24) may be used uninitialized in this function [-Werror=maybe-uninitialized]
                rtree.qbegin(bgi::intersects(box));
                             ~~~~~~~~~~~~~~~^~~~~

Change-Id: I2bb2a77215cbb53ce790913d6e67c7afe3f94d2d
(cherry picked from commit 6ca22148365b58a0405644cc77a9bf0fae76d6ba)