WL#8726
 - compiler error detected with -Werror=logical-op since "index" can't
   be both larger than zero and smaller than NO_OIF_BLOCKS at the same
   time.

   storage/ndb/src/common/debugger/DebuggerNames.cpp:92: error: logical
   'and' of mutually exclusive tests is always
   false [-Werror=logical-op]
      if((index < 0 && index >= NO_OF_BLOCKS) || dst[index] != 0)
                       ^
  - fix by changing to an or and removing the unnecessary parentheses
    since each condition is faulty in it's own right.
  - the parenteses was added to fix gcc 4.4 compiler warning...

(cherry picked from commit 2611877853601a45ec29d8144a2eee498f81373b)