A blind attempt to fix a compilation error on 64-bit Windows:
24>.\handler\ha_innodb.cc(11200) : error C2440: 'initializing' : cannot convert from 'ulint *' to 'unsigned long *'