Bug#33282549 MySQL Cluster 7.4 fail to build with GCC 10 and 11
Build MySQL Cluster 7.4 with GCC 10 or 11 fails with narrowing error.

    src-7.4/storage/ndb/src/mgmapi/ndb_logevent.cpp:516:10: error: narrowing
conversion of ‘NDB_MGM_ILLEGAL_EVENT_CATEGORY’ from ‘int’ to ‘unsigned int’
[-Wnarrowing]

It turns out that compile is not using g++03 mode as expected.

After change to cmake file to ensure g++03 mode error was also turned into
warning and not blocking build (with MYSQL_MAINTAINER_MODE off).

Change-Id: Ia3355887f5864e4c7b8eb5a0c51ce26c1932985d