Bug#35855488 Build on Ubuntu 23.10 [noclose]
sql-common/oci/signing_key.cc:87:42: error:
ignoring attributes on template argument int (*)(FILE*)
[-Werror=ignored-attributes]
std::unique_ptr<FILE, decltype(&fclose)> fp(fopen(file_name.c_str(), "rb"),

This is the declaration for Ubuntu 23.10
extern int fclose (FILE *__stream) __nonnull ((1));

Use a scope guard closure, rather than a unique_ptr with custom deleter.

Change-Id: Iecb41b238dc9b72d87f33f54aea272391f3b5977
(cherry picked from commit 5d2e8c1aadb23c9d9acba692d2dd7afb24a0897a)