Include missing headers breaking VS2019 version 16.6 nightly builds
Include the right headers in kdf_sha_crypt.cc:
* <stddef.h> for size_t
* <cstdlib> for std::strtol
* <tuple> for std::tie            (this is the one that broke the build)
* <iterator> for std::distance

Include the right headers in kdf_pbkdf2.cc:
* <stdint.h> for uint8_t
* <cstdlib> for std::strotl
* <tuple> for std::tie            (this is the one that broke the build)
* <iterator> for std::distance

F:\gitP\mysql\mysql-server\router\src\http\src\kdf_sha_crypt.cc(71): error C2039: 'tie': is not a member of 'std' [F:\gitP\mysql\mysql-server\build_amd64\router\src\http\src\http_auth_backend_lib.vcxproj]
F:\gitP\mysql\mysql-server\router\src\http\src\kdf_sha_crypt.cc(71): error C3861: 'tie': identifier not found [F:\gitP\mysql\mysql-server\build_amd64\router\src\http\src\http_auth_backend_lib.vcxproj]
F:\gitP\mysql\mysql-server\router\src\http\src\kdf_pbkdf2.cc(79): error C2039: 'tie': is not a member of 'std' [F:\gitP\mysql\mysql-server\build_amd64\router\src\http\src\http_auth_backend_lib.vcxproj]
F:\gitP\mysql\mysql-server\router\src\http\src\kdf_pbkdf2.cc(79): error C3861: 'tie': identifier not found [F:\gitP\mysql\mysql-server\build_amd64\router\src\http\src\http_auth_backend_lib.vcxproj]