Bug#32663921 mysql-4.0 client-greeting decode missing nul-terminator
Issue
=====

When a 3.23/4.0 client connects to the mock-server without specifying an
initial schema, it closes the connection and reports:

  Error: missing nul-terminator

The decoder for client::Greeting wrongly expects a nul-terminator.

Issue
=====

- use the shared-capabilities instead of the server-capabilities to
  check if the client is sending a schema-name
- added tests to verify more combinations

RB: 26119