Post push fix for compile error:
MgmtSrvr.cpp:3094: error: expected unqualified-id before 'return'
MgmtSrvr.cpp:3095: error: expected declaration before '}' token

Moving #ifdef ERROR_INSERT to a better åplace.

Affects earlier commits:
commit 51655ae110cfb3fac5de5530fefb89465be6209e
commit d3f8fc2c8351e9a11a8dbbb00f7c54b1978f2a55