WL#14772: InnoDB: Parallel Index Build
Post-push fix for broken clang -Werror build:

page0size.h:213:3: error: definition of implicit copy assignment operator for 'page_size_t'
is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]

storage/innobase/include/buf0buf.h:1272:10: note:
in implicit copy assignment operator for 'page_size_t' first required here
    size = page_size;

storage/innobase/ddl/ddl0builder.cc:2824:12: error:
variable 'total_rows' set but not used [-Werror,-Wunused-but-set-variable]

Change-Id: I44dd7399dae189a8291d0e5329de45194e0fe4a2