part of WL#6347 InnoDB: Index level compression stats
Fixup compilation err on Windows:

57>..\..\..\mysql-5.7.0-m10\storage\innobase\page\page0zip.cc(27) :
error C2871: 'std' : a namespace with this name does not exist