WL#5769: Keyring service for MySQL WL#8821: Innodb tablespace encryption key rotation          SQL commands WL#8548: InnoDB: Transparent data encryption
Post-push fix: Fix warnings reported by Clang

sql/sql_alter_instance.h:16:9: error:
      'SQL_ALTER_INSTANCE_INCLUDED' is used as a header guard here, followed by #define of a
      different macro [-Werror,-Wheader-guard]
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~

plugin/keyring/keyring.cc:18:
/export/home/repo/mysql-ubsan/plugin/keyring/keyring.h:26:17: error: using namespace directive
      in global context in header [-Werror,-Wheader-hygiene]
using namespace keyring;
                ^

plugin/keyring/keyring_impl.cc:229:6: error: dereference of type
      'uchar **' (aka 'unsigned char **') that was reinterpret_cast from type 'void **' has
      undefined behavior [-Werror,-Wundefined-reinterpret-cast]
    *reinterpret_cast<uchar **>(key)=fetched_key->release_key_data();
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~