BUG#32405805 BROKEN MTR XML-REPORT AND JUNIT PARSING
Having < or " in the test comments fails

Examples:
    <testcase name="tls12_tls1" status="skipped" time="0" suitename="auth_sec" comment="Test requires TLS protocol <= 1.1, while OpenSSL policy sets MinProtocol TLSv1.2" />
    <testcase name="set_password-bug27820277" status="skipped" time="0" suitename="i_main" comment="Need '--valgrind' " />

Returns:
    org.dom4j.DocumentException: Error on line 106 of document  : The value of attribute "comment" associated with an element type "testcase" must not contain the '<' character.
    org.dom4j.DocumentException: Error on line 2968 of document  : Element type "testcase" must be followed by either attribute specifications, ">" or "/>".

Change-Id: Ia3bfd3d4c8494e3d9ccaee31f20967ccf08af46a