Bug #33574176 Compile MySQL with GCC 12
Fix compiler warnings for Debug -O2 -flto

Silence -Wstringop-overread for a router unit test.
This looks like a gcc12 bug, when doing Debug builds with -O2
and link-time optimization.

Similarly for linking mysqlbinlog.
For both Debug and RelWithDebInfo builds:
my_time.h:202:19: error:
__builtin_strncpy specified bound depends on the length of the source argument [-Werror=stringop-truncation]
mysqlbinlog.cc:2169:22: note: length computed here

There are two calls to convert_str_to_timestamp. Commenting out either
one of them, and there is no warning.

sql_servers.cc:946:23: error:
'%s'directive argument is null [-Werror=format-overflow=]

ndb/src/common/portlib/NdbEnv.cpp:36:12: error:
__builtin_strncpy specified bound 100 equals destination size [-Werror=stringop-truncation]

storage/innobase/arch/arch0arch.cc:74:37: error:
%s directive output may be truncated writing up to 98 bytes into a
region of size between 1 and 99
[-Werror=format-truncation=]
   74 |   snprintf(path, sizeof(path), "%s%c%s", file_path, OS_PATH_SEPARATOR,
Removing the debug assert (ut_ad(...)) also removes the warning.
The solution is to reduce level of -Wformat-truncation for this particular source file.

Change-Id: I1d4ba0a46dc9334b51d1c317c8916db7441c1406
(cherry picked from commit d1a8074993f143e2d09afecf2b2876e9fe037c18)