Bug#34099162 Add support for mold linker
Add a cmake option -DWITH_LD=mold|lld.
The default is empty, i.e. use the standard linker.
The new option is only visible on Linux.

Remove the cmake option -DUSE_LD_LLD, use -DWITH_LD=lld instead.

Note that for el7/el8/el9 we use compilers from /opt/rh/devtoolset...
and must use the 'ld' linker that comes with that bundle.
Hence alternative linkers like 'lld' and 'mold' cannot be used,
and -DWITH_LD is not available as an option.

Fix a linker warning for 'mysql_ssl_rsa_setup' with lto:
mold: warning: symbol type mismatch: error
>>> defined in /tmp/ccbfnLqs.ltrans0.ltrans.o as STT_OBJECT
>>> defined in /lib64/libc.so.6 as STT_FUNC

Silence -Wno-alloc-size-larger-than warnings for
mysqld and server_unittest_library.
sql/rpl_info_values.cc:45:44: error: argument 1 value
 18446744073709551615
 exceeds maximum object size 9223372036854775807
 [-Werror=alloc-size-larger-than=]

Change-Id: I49bc677194624f944f345ef50b9004575776f736