Bug#36053908 Windows ndb_sign_keys assert(!running()) fails.
Post-push fix for broken build with clang on Windows.
NdbProcess.hpp(126,40): error:
missing field 'hThread' initializer [-Werror,-Wmissing-field-initializers]

Initialize all the fields of:

typedef struct _PROCESS_INFORMATION {
  HANDLE hProcess;
  HANDLE hThread;
  DWORD  dwProcessId;
  DWORD  dwThreadId;
} PROCESS_INFORMATION, *PPROCESS_INFORMATION, *LPPROCESS_INFORMATION;

Change-Id: I97d444671b59b2d16be7524012a83ccbb5db443f