WL#15924 Support upgrade from 8.x only
Post-push fix for broken clang build:

storage/innobase/dict/dict0load.cc:1432:26:
error: unused function 'dict_check_sys_tables' [-Werror,-Wunused-function]

Change-Id: Ibc125ce33a5859d94477035297a7c61dc014311b