Bug #32552988 ADD SUPPORT FOR GCC 10 ON SOLARIS
Additional patch for ndbcluster:

Fix two build breaks:

NdbThread.cpp
error: comparison of integer expressions of different signedness:
'id_t' {aka 'int'} and 'Uint32' {aka 'unsigned int'} [-Werror=sign-compare]

DblqhMain.cpp
error: comparison of unsigned expression in '< 0' is always false
[-Werror=type-limits]

Disable VM_TRACE in ndbd_malloc_impl.cpp for Solaris builds.
Filed a bug for it:
Bug #32575486 NDBMTD CONSUMES ALL AVAILABLE MEMORY IN DEBUG ON SOLARIS

Change-Id: Ib80061dd0934473d11e71bb5d7ed2e9d1b23b3bb