Bug #33574176 Compile MySQL with GCC 12 [noclose]
Make MySQL compile with GCC 12. Note that there are still quite a few
warnings left, especially what appears to be false positives in
Google Test mocks and matchers.

Note also that binaries in RelWithDebInfo do not work.
The first obstacle seems to be get_defaults_options()
This loop is exited prematurely
   while (argc >= 2 && argc != prev_argc)
we we fail to load --defaults-file=...../my.cnf
and then nothing works after that.

Fixes done:
 - disable -Wdangling-pointer for extra/lzma/LzmaEnc.c:2828
 - disable -Warray-bounds for InnoDB code used from meb.
 - deriving from std::iterator is deprecated.
   Implement iterator traits types in sql/dd/collection.h
 - disable -Wmaybe-uninitialized for some boost gis code.
 - fix a -Werror=restrict warning in Item_func_get_dd_create_options::val_str
   by adding an explicit conversion of "N" to dd::String_type()
 - sql/rpl_info_values.cc:44:43: error: '<anonymous>'
   may be used uninitialized [-Werror=maybe-uninitialized]
   The fix was to use new (std::nothrow)
 - sql/log_event.cc:5141:1: error: dangling pointer to an unnamed temporary
     may be used [-Werror=dangling-pointer=]
   The fix is to switch from std::initializer_list<std::string> to
     std::initializer_list<std::string_view> in
   Applier_security_context_guard::has_access()
 - sql/spatial.h:734:13: error: 'void* memset(void*, int, size_t)' offset [0, 7]
   is out of the bounds [0, 0] [-Werror=array-bounds]
 - storage/innobase/fts/fts0opt.cc:2599:9:
   compiler error: in cp_gimplify_expr, at cp/cp-gimplify.c:747
 - storage/myisam/ha_myisam.cc:1216:25: error:
   using a dangling pointer to 'buf' [-Werror=dangling-pointer=]
 - graph_simplification-t.cc:135:27: error: '%d' directive output may be truncated
   writing between 1 and 11 bytes into a region of size 9 [-Werror=format-truncation=]

With these fixes, the Debug build is warning free.
The RelWithDebInfo is warning free if built with -DWITH_UNIT_TESTS=OFF

Change-Id: I3f2d35321e2010ab48e2b0155f52461f052881b1
(cherry picked from commit c098e7f8da81f7840fa4ce84daacac17a854d08a)