Bug #32729945 FIX BUILD WARNINGS FROM GCC 11
Buiding with gcc11, we get misc new warnings.
This patch fixes additional warnings for RelWithDebInfo builds with:

-DCMAKE_CXX_FLAGS="$(rpm --eval %optflags)"

Which evaluates to

-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches
 -pipe -Wall -Werror=format-<hide-this-option> -Wp,-D_FORTIFY_SOURCE=2
 -Wp,-D_GLIBCXX_ASSERTIONS
 -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1
 -fstack-protector-strong
 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic
 -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection

Note the -flto and "fortify source".

Warnings fixed:

[-Werror=odr] for libserver_unittest_library.so
There are known ODR violations because of multiple bison parsers.
Downgrade to warning, so we can see possible other violations.

[-Werror=odr] for firewall.so
This plugin is built with both plugin and component services:
Fixed by adding PLUGIN_GLOVE to target defines for "glove" plugins.

[-Werror=maybe-uninitialized]
prealloced_array.h:218:47: error:  may be used uninitialized
  218 |     if (!using_inline_buffer()) my_free(m_ext.m_array_ptr);
Which was caused by LEX_MASTER_INFO lex_mi;
in sql/rpl_channel_service_interface.cc:420:19
Fixed by adding default initializer to 'm_ext' in the anonymous union.

[-Werror=maybe-uninitialized] in group_replication/libmysqlgcs
Fixed by using calloc() rather than malloc().

Misc other [-Werror=maybe-uninitialized] fixed by adding {} to stack
variable declarations.

Misc [-Werror=stringop-truncation] fixed by adjusting string length
calculations, or switching from stpncpy to snprintf (which is safer).

Lots of warnings for the xclient_unit_tests executable.
Disabled -flto, and filed a separate bug for it.

Change-Id: Ifbbf29a27e0ab36765a6bb49a4bd54c307cbfc6b