Bug #34336718 Upgrade the bundled googletest sources to 1.12.0
Upgrade the bundled googletest/googlemock source to the most recent version,
which is currently 1.12.0

The workaround for -Werror=maybe-uninitialized for googlemock matchers
can be removed, the bug has been fixed upstream.

git add extra/googletest/googletest-release-1.12.0/googlemock/
git add extra/googletest/googletest-release-1.12.0/googletest/
git rm -rf extra/googletest/googletest-release-1.12.0/googlemock/test
git rm -rf extra/googletest/googletest-release-1.12.0/googletest/test

git rm -rf extra/googletest/googletest-release-1.11.0

Visual Studio fails to compile any usage of testing::WithArgs<0, ...>
gmock-actions.h(1432,59):error C2039: 'type' is not a member of 'std'

The workaround is to add extra arguments to:
  Mock_dd_field_varstring::fake_store()
  Mock_dd_field_varstring::fake_val_str()
so that we can remove WithArgs<0> and WithArgs<1>.

Similarly for
  mock_gcs_xcom_state_exchange_interface::free_xcom_member_state()
  mock_gcs_xcom_state_exchange_interface::free_members_joined()
  suspect_is_me()
  suspect_is_2()
  copy_message_content()

The macro GTEST_DISALLOW_COPY_AND_ASSIGN_ is no longer provided by
googletest headers. The fix is to expand the old definition of the
macro at all places it was used.

Some source file need COMPILE_FLAGS "/bigobj" with Visual Studio.

Change-Id: Id078f63163e672ac6949901c664a712a00ec4d72
(cherry picked from commit 69ef1a1621b85be54dbdb32a26acaee099f40f6c)