Bug#34566244 fixed range-loop-bind-reference warnings
Issue
=====

If -Wrange-loop-analysis is enabled with clang, it reports warnings for:

- access_rights.h
- mysql_client.h

error: loop variable 'row' binds to a temporary value produced by a
range of type 'MysqlClient::Statement::Rows'
[-Werror,-Wrange-loop-bind-reference]

Both implement iterators which return a copy an temporary object,
instead of a reference.

Change
======

- enable -Wrange-loop-analysis when building with clang.
- change operator!= to const
- change iterators to return references an internal object

Change-Id: I23069f3a5494004ea764f0ca167e26f7b9f50dad