Bug #33110341 UTILIZE INNODB LIBRARY FOR DYNAMIC STORAGE MANAGEMENT OF SUITABLY ALIGNED TYPES
Post-push fix for narrowing issue uncovered in 32-bit EL6 builds.

  error: narrowing conversion of '(end_lsn - ((long long unsigned int)start_lsn))'
  from 'lsn_t' {aka 'long long unsigned int'} to 'size_t' {aka 'unsigned int'}
  inside { } [-Werror=narrowing]

Both end_lsn and start_lsn are uint64_t and arithmetic between them
along with brace-initialization doesn't fly because their result cannot
fit into the size_t, which in 32-bit builds is less than 64-bits, in
particular it is 32-bit wide.

Modifying ut::Count to operate on uint64_t instead of size_t seems like
an easy fix but it doesn't make much sense given that size_t is the
smallest integer that represents the largest object size. Being able to
allocate more bytes than one can address does not make much sense.

Patch is therefore silencing the narrowing issue by avoiding the brace-
initialization in this particular case. In case that difference between
end_lsn and start_lsn would in some unlikely event be larger than 2^32-1,
code will have bigger problems to solve.

Change-Id: I6ec5c0f81703a63affd524dfdb5e0e8a9064a5d6