Partially fix Bug#19579603 NEW INNODB COMPILE WARNINGS WITH CLANG 3.5
Do not memset() the rtr_info_t object in rtr_init_rtr_info() because it contains an ib_mutex_t object and this causes the following warning with clang 3.5:

/bzrroot/server/mysql-trunk/storage/innobase/gis/gis0sea.cc:1005:10: error: destination for this 'memset'
      call is a pointer to class containing a dynamic class 'DebugPolicy<TTASEventMutex<DebugPolicy> >';
      vtable pointer will be overwritten [-Werror,-Wdynamic-class-memaccess]
                memset(rtr_info, 0, sizeof(*rtr_info));
                ~~~~~~ ^

Instead of the memset() explicitly assign each member to 0, NULL or false except the mutex, which is passed to mutex_create().

Approved by:	Kevin (RB#6647)