Bug#37032925 on windows ProcessLauncher modifies the parent env
Post-push fix, clang on win said

process_launcher.cc(263,19): error: loop variable '[key, val]' creates
 a copy from type 'const value_type'
 (aka 'const std::pair<std::basic_string<char>,
 std::basic_string<char>>')
 [-Werror,-Wrange-loop-construct]
  for (const auto [key, val] : env_vars) {
                  ^
note: use reference type 'const value_type &'
(aka 'const std::pair<std::basic_string<char>, std::basic_string<char>> &') to prevent copying

Change-Id: I6cc89f4aacfae396c3b14815dab20ab7e574d68d
(cherry picked from commit 9439a58337bc7bfd13242c61ec40f152f2ca5a1f)