Fix compilation failure when UNIV_MEM_DEBUG is defined:
innorwlocktest.cc:546:22: error: macro "mutex_create" passed 3 arguments, but takes just 2
innorwlocktest.cc: In function 'int main(int, char**)':
innorwlocktest.cc:543: error: 'mutex_create' was not declared in this scope