Bug#36108397 Upgrade to latest protobuf library [8.0 patches]
Patch for 8.0 only.

Additional patch for build problems with gcc8 on el6:

linking runtime_output_directory/protoc-24.4.0
libprotobuf.so.24.4.0: undefined reference to
absl::lts_20230802::Cord::InlineRep::AppendArray(
  absl::lts_20230802::string_view,
  absl::lts_20230802::cord_internal::CordzUpdateTracker::MethodIdentifier)

whereas libabsl_cord.a defines:
absl::lts_20230802::Cord::InlineRep::AppendArray(
  std::basic_string_view<char, std::char_traits<char> >,
  absl::lts_20230802::cord_internal::CordzUpdateTracker::MethodIdentifier)

The solution is to build everything with -std=c++17, to avoid
any use of absl::string_view

Change-Id: I9ecea4ba58a91300d673864c571b11cabc5b8392