Bug#27874068 ADD SUPPORT FOR -DCMAKE_BUILD_TYPE=RELEASE
Post-push fix: after changes in compile flags, we have to look explicitly
for 'dlsym' in addition to 'dlopen', so that LIBDL is set to '-ldl'

got link errors for ASAN build:
libmysqlclient.so.21.0.13: error: undefined reference to 'dlsym'

Also, fix ASAN error in mysqltest:
don't read past-the-end of 'buf' when running with --debug.

Change-Id: I4bf67af82ba6c93d3182768133c047421e2ffb4a