Followup to sunny.bains@oracle.com-20131210092144-0xfzdmj5vgqlqpq2
Fix a compilation failure on Win32:

  buf0buf.ic(1016): error C2664: '_InterlockedExchangeAdd' : cannot
  convert parameter 1 from 'ib_uint32_t *' to 'volatile long *'
  Types pointed to are unrelated; conversion requires reinterpret_cast,
  C-style cast or function-style cast