Bug#28277893: GCC 8 WARNING IN MYSQL_CLIENT_TEST.CC
GCC 8.1 emits the following warning when building MySQL with the -Og
compiler option:

testclients/mysql_client_test.cc: In function ‘void test_mem_overun()’:
testclients/mysql_client_test.cc:7842:20: error: ‘%d’ directive writing between 1 and 11 bytes into a region of size 9 [-Werror=format-overflow=]
     sprintf(field, "c%d int", i);
                    ^~~~~~~~~
testclients/mysql_client_test.cc:7842:20: note: directive argument in the range [-2147483648, 999]
testclients/mysql_client_test.cc:7842:12: note: ‘sprintf’ output between 7 and 17 bytes into a destination of size 10
     sprintf(field, "c%d int", i);
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

Fix it by changing the type of the loop variable from int to unsigned
int, so that the compiler more easily sees that it's in the range [0,
999] and not [-2147483648, 999].

Change-Id: Id8f178da04bb2095075d11adeef06ce2dbbbe3ad