Bug #34278103 Compile MySQL with GCC 13 [noclose]
sql/item_strfunc.cc:793:33: error:
length may be used uninitialized [-Werror=maybe-uninitialized]

Rewrite/simplify error handling in
Item_func_to_base64::val_str_ascii() and
Item_func_from_base64::val_str().

Change-Id: I660ea3e503ca292f6a02498be7406fe7e10a4b6c
(cherry picked from commit f457487f5ccf26abeb4b7655e2dad47c642da7f4)