Bug#36664672 Build break on Fedora 40 with debug and system libs
Use MY_Z_NULL in our own source code, to avoid macro redefinition:

In file included from <...>/mysql/storage/archive/ha_archive.h:32,
                 from <...>/mysql/storage/archive/ha_archive.cc:26:
<...>/mysql/storage/archive/azlib.h:198:9: error: "Z_NULL" redefined [-Werror]
  198 | #define Z_NULL 0 /* for initializing zalloc, zfree, opaque */
      |         ^~~~~~
In file included from <...>/mysql/storage/archive/ha_archive.h:25:
/usr/include/zlib.h:223:9: note: this is the location of the previous definition
  223 | #define Z_NULL  NULL  /* for compatibility with zlib, was for initializing zalloc, zfree, opaque */
      |         ^~~~~~

Change-Id: Ie333897dea2a8f29a07b3e8e90441396c19ed8f2
(cherry picked from commit 4975f4ccec48a3f307cac65ec5a55a5e925301cf)