Bug#20685187 USE -STD=C99 WHEN BUILDING WITH GCC ON SOLARIS
The patch for
    Bug #19573096: LOADING CORRUPTED GEOMETRY DATA INTO A
                   MYISAM TABLE CAUSES THE SERVER TO CRASH
Introduced a build break on solaris:
myisam/rt_split.c:69:3: error: implicit declaration of function 'isinf'
[-Werror=implicit-function-declaration]

The error goes away when building with -std=c99