Bug#27470071 ERROR C1083: CANNOT OPEN INCLUDE FILE: 'LEX_TOKEN.H'
This is a bacport to 5.6 of four bugfixes in 5.7

    Bug#20678411 BROKEN MAKEFILE DEPENDENCY: SQL_YACC.YY AND LEX_TOKEN.H
    Add explicit dependency sql_yacc.cc.o => lex_token.h

    Bug#19060850: SQL_YACC.CC REGENERATED TWICE IN WINDOWS BUILD, CAN LEAD TO BUILD BREAK
    Run Bison separately for libmysqld so that independent copies of
    sql_yacc.h/sql_yacc.cc are generated. This avoids the Windows
    build break because of libmysqld compilation of sql_yacc.cc while
    it is being generated.

    Bug#21680733 WINDOWS (10) BUILD MAY COMPILE SQL_YACC.CC BEFORE LEX_TOKEN.H HAS BEEN GENERATED
    Problem: build may fail non-deterministically when when building in parallel.
    Solution: build local copy lex_token.h, and add explicit dependency for it.

    Bug#24931655 RACE CONDITION BUILDING LEX_HASH.H
    Mysql cluster is experiencing race conditions generating lex_hash.h
    Fix:
    Generate lex_hash.h locally for the embedded server,
    rather than picking it up from the sql/ build directory.