Bug#28707282 BUILD FAILURE WITH -WERROR FLAG ENABLED
Replace use of MEMCOPY_NO_WORDS with std::memmove in Trix.cpp.

Via MEMCOPY_NO_WORDS memcpy was used for copying memory areas there source and destination overlap.

This was detected by compiler warnings (turned into errors) like:

In function 'void* memcpy(void*, const void*, size_t)',
    inlined from 'void Trix::execDUMP_STATE_ORD(Signal*)' at
../../../../../../mysql-cluster-com-8.0.14-dmr/storage/ndb/src/kernel/blocks/t
rix/Trix.cpp:481:5:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:34:33: error: 'void*
__builtin_memcpy(void*, const void*, long unsigned int)' accessing 40 bytes
at offsets 40 and 44 overlaps 36 bytes at offset 44 [-Werror=restrict]
   return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~