Bug#35599395 Change literal 0 to nullptr where appropriate [noclose]
Post-push fix for
    WL#14717 - InnoDB: Bulk Ingest Feature V1
which enabled some debug print code not fixed for NULL/nullptr earlier.

Link bulk_loader_lib with extra::rapidjson, so that sources in
bulk_loader_lib get proper DEFINITIONS, OPTIONS and INCLUDES from the
INTERFACE library.

Silence these warnings in aws/s3.cc
  error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
This should have been a property of extra::rapidjson, but that may
lead to buld breaks, since there is still some C code linking with it.

The source file aws/s3.cc is now built with the correct #defines for rapidjson,
so it must include my_rapidjson_size_t.h

Fix one error reported by clang 16
s3.cc:467:10: error: variable 'count' set but not used [-Werror,-Wunused-but-set-variable]

Change-Id: Idd870f6f7709157cfe3e0492a4f7107d1b3d795a