Bug#36292498: Compile MySQL with clang 18 [noclose]
Fix compilation error by adding missing #include for std::find.

router/tests/helpers/tcp_port_pool.h:112:14: error: no matching function for call to 'find'
  112 |       return std::find(std::begin(id_), std::end(id_), id) != std::end(id_);
      |              ^~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/streambuf_iterator.h:435:5: note: candidate template ignored: could not match 'istreambuf_iterator' against '__normal_iterator'
  435 |     find(istreambuf_iterator<_CharT> __first,
      |     ^
1 error generated.

Change-Id: I630ff8ec78190951eefae5c228606f5e7559304d
(cherry picked from commit 958d8d86c25db5bbf6c776338e9cb4dee6fef797)