Bug#37038385 stack-use-after-scope in test_http_request_router.cc
ERROR: AddressSanitizer: stack-use-after-scope on address 0x7fede52a195a
at pc 0x7fede8fd25b0 bp 0x7ffec90ba9f0 sp 0x7ffec90ba9e8
READ of size 2 at 0x7fede52a195a thread T0
    #0 0x7fede8fd25af in icu_73::RegexMatcher::MatchChunkAt(int, signed
char, UErrorCode&)
/extra/icu/icu-release-73-1/source/i18n/rematch.cpp:4416:25

Matcher->reset() expects that the input-string is kept alive until the
next reset.

As ->reset("/foo") creates a temporary UnicodeString it gets destroyed
before ->find() is called leading to a "stack-use-after-scope".

Change
======

- construct the UnicodeString before calling the ->reset() and keep it
  alive until after ->find() to avoid the stack-use-after-scope

Change-Id: I92b0000fe980135c6a717840a10cbbcb544c165d