Bug#36082229 Check there are no active error inserts set after NDBAPI test run
Fix compilation error due to C++11 syntax
   storage/ndb/test/include/NDBT_Test.hpp:329: error: expected ';'
before 'override'

Change-Id: Ifa4e1c594809a0467d0efd7fce1a5e425f03e112