WL#7777 Integrate PFS memory instrumentation with InnoDB
Avoid compilation error:

/bzrroot/server/mysql-trunk-wl7777/storage/innobase/include/ut0new.h:217:7: error: cannot define the
      implicit copy assignment operator for 'ut_allocator<std::_Rb_tree_node<dict_foreign_t *> >', because
      non-static const member 'm_key' can't use copy assignment operator

when ut_allocator is used in a constructs like:

typedef std::set<
        dict_foreign_t*,
        dict_foreign_compare,
        ut_allocator<dict_foreign_t*> > dict_foreign_set;