Bug#35479763 el7 aarch64 might return invalid for value cache line causing crash during boot
Additional patch: Debian/Ubuntu build failed with:
error: ignoring return value of 'int fscanf(FILE*, const char*, ...)'
declared with attribute 'warn_unused_result'

Change-Id: I51c9c72642014b26b7bcfec49ba3491db47e4632
(cherry picked from commit 1300daf00f3d6a7d15222a962be9f23dbe0cf339)