Bug#20193236 SOME COMPILER WARNINGS BECAME ERRORS AFTER MERGE OF MYSQL SERVER 5.5.41
After merge of MySQL server 5.5.41 into Cluster 7.2 some warnings became
errors for debug build (maintainer mode) in cluster specific parts
(MCP_WL3749) of sql/sql_table.cc.

Building with g++-4.3.6 failed with:
error: suggest a space before ';' or explicit braces around empty body in ?for? statement

Building with g++-4.6.4 failed with:
error: variable 'old_db_type' set but not used [-Werror=unused-but-set-variable]

This patch do non functional changes to avoid these warnings/errors.