Bug #31930934 COMPILATION FAILED ON UBUNTU
error: passing const Key_map
{aka const Bitmap<256>} as this argument discards qualifiers [-fpermissive]

Fix: add missing const specifier to the get_first_set() member function.

Change-Id: If0b6bed6b28122a50f834d79ab71282f3681e1b2