Bug#35817210: Fix compiler warnings from clang 17
strings_utf8-t.cc:201:26: error: identifier '_sl' preceded by
whitespace in a literal operator declaration is deprecated
[-Werror,-Wdeprecated-literal-operator]

Fixed by switching to the non-deprecated syntax.

gcs_xcom_control_interface-t.cc:1252:17: error: reference cannot be
bound to dereferenced null pointer in well-defined C++ code;
comparison may be assumed to always evaluate to true
[-Werror,-Wtautological-undefined-compare]

Fixed by removing the assertion.

Change-Id: I784375ccc8c015ddf3b68cddf3c55ef751d5cb55
(cherry picked from commit f1d0de10b0b57d1fce2b79f9a79d1410715a7b99)