Bug#36480358: Compile MySQL with GCC 14 [noclose]
RelWithDebInfo and LTO:

storage/ndb/src/ndbapi/Ndb.cpp:489:11: error: 'buf_209' may be used uninitialized [-Werror=maybe-uninitialized]
  489 |   md5_hash(values, (const char *)buf, len);

storage/ndb/src/common/mgmcommon/thr_config.cpp:1458:36:
error: '%s' directive argument is null [-Werror=format-overflow=]
 1458 |       printf("do_parse(%s) => %s - %s\n", fail[i], res == 0 ? "OK" : "FAIL",

Linking CXX shared library ../../../../library_output_directory/libmysqlrouter_mysqlxclient.so
In member function __ct ,
    inlined from __ct  at /usr/include/c++/14/bits/stl_pair.h:444:35,
    inlined from get_connect_attrs at plugin/x/client/xsession_impl.cc:1115:1:
plugin/x/client/mysqlxclient/xargument.h:38:7:
error: 'D.13743.m_value' is used uninitialized [-Werror=uninitialized]
   38 | class Argument_value {

The warnings in storage/ndb are false positives, downgrade from error to warning.
Fix the warning in plugin/x/client by adding an initializer to Argument_value::m_value;

Change-Id: I3296022a6b852dd46a7790c4912b1e4aa7260a65
(cherry picked from commit 253f546a68efa5759ded7ddbc8efb1bc5c773095)