Bug#29250460: CLANG 7 + VISUAL STUDIO 15.9 DOES NOT BUILD
Building with Clang 7 + Visual Studio 15.9+ gives compilation errors
when building Boost:
error: no template named 'basic_string_view' in namespace 'std'

The root cause is that Boost gets confused about the level of C++
language support it is compiled with, and does not set a macro
symbol (BOOST_NO_CXX17_HDR_STRING_VIEW) as it should.

This patch fixes the problem by defining the symbol explicitly.

Change-Id: I0386abf4defc684924335318cc36a50409df4524