Bug#35185670 mysqld crashes on expensive query
Post-push fix for broken build on MacOS:

SectionIterators.cpp:421:7: error: variable 'signals' set but not used
[-Werror,-Wunused-but-set-variable]
  int signals= 0;

Change-Id: I478ad78672d7fc9875d8d289aae233f679dd64a9
(cherry picked from commit ce9b0de3addd6a72917079fdcd188282d320667a)