Post-push fix for Bug#22084822 AUTOTEST TESTNODERESTART -N BUG18612SR SOMETIMES DID NOT CLEAR ERROR.
Comparisons between signed and unsigned integer introduced in
previous patch are now changed to comparisons between signed
integers.

NdbRestarter.cpp: In member function 'int NdbRestarter::insertErrorInNodes(const int*, int, int)':
NdbRestarter.cpp:742: error: comparison between signed and unsigned integer expressions
NdbRestarter.cpp: In member function 'int NdbRestarter::insertError2InNodes(const int*, int, int, int)':
NdbRestarter.cpp:797: error: comparison between signed and unsigned integer expressions