Bug#34114909 Fix compiler warnings from clang on Windows [noclose]
BUG#36357137 - http_plugin should stop using libevent in favor of net_ts

Post-push fix for broken clang/windows build:
con/error_code.h(35): error:
'nodiscard' attribute cannot be applied to types

Change-Id: Ib39b4f84b497353b0657ef41d04798fab7c9487c
(cherry picked from commit 006230b1ec241fb15f0303569a4bf6a12bd552e8)