Bug #20504741 Bug #20695155 Improve Clusterj handling of ByteBuffers to reduce direct memory footprint Fix Clusterj incompatibility with Java 7
Implement two kinds of buffer pool:
  fixed-sized buffers
    used for NdbRecord and Decimal scratch buffers
  variable-sized buffers
    used for Blob when reading and writing data
Configuring the variable-sized buffers is done via connection properties

Work around a bug in handling Blob columns with NdbRecord
  the size of blob is incorrectly calculated to be 16 bytes plus 256 inline size
    this calculation should include only the 16 byte Blob header
  the incorrect calculation makes the total size of the NdbRecord
    larger than needed, which affects the nextRecordCopyOut method
    to write more data than it should
  with java 6 each direct ByteBuffer is aligned on page boundary
  with java 7 onward, direct ByteBuffers are packed so writing more data
    corrupts the following memory which crashes the vm

Constants.java
  add connection property com.mysql.clusterj.byte.buffer.pool.sizes
    with default 256, 10K, 100K, 1M

SessionFactoryImpl.java
  initialize variable buffer pool for cluster connection

ClusterConnection.java
  add method setByteBufferPoolSizes(int[] poolSizes)

core/Bundle.properties
  add message for invalid variable byte buffer pool sizes

BlobImpl.java
  add variable buffer pool to constructors
  use variable buffer pool to read and write blob data

ClusterConnectionImpl.java
  implement method setByteBufferPoolSizes(int[] poolSizes)
  initialize variable byte buffer pool
  implement method getByteBufferPool()

ClusterTransactionImpl.java
  implement method getClusterConnection()

ColumnImpl.java
  change space allocation for blobs to include only the blob header

NdbRecordBlobImpl.java
  add variable byte buffer pool to constructor

NdbRecordDeleteOperationImpl.java
  use fixed buffer pool for delete key instead of direct allocation

NdbRecordImpl.java
  use fixed byte buffer pool for NdbRecord value and key buffers
  use new Utility method for BigDecimal and BigInteger conversions
    the new methods pass ByteBuffer instead of allocating new buffers
  calculate the size for NdbRecord but also check it against
    the size from NdbDictionary; warn if the values are different
  release the buffer pool when the table is unloaded due to schema change

NdbRecordIndexScanOperationImpl.java
  return the key (index) buffers used to define the scan after definition

NdbRecordOperationImpl.java
  initialize the variable buffer pool in the constructor
  release the value buffer and any key buffers when the owning object
    is garbage collected

NdbRecordScanOperationImpl.java
  change the order of releasing resources: this first; superclass afterward

NdbRecordScanResultDataImpl.java
  close the ScanOperation java object instead of the ndb object

OperationImpl.java (used for non-NdbRecord access)
  plan for the variable byte buffer pool (not currently implemented)

ResultDataImpl.java
  implement the new constructor for Blob

Utility.java
  add new methods to convert BigDecimal and BigInteger
    new methods take ByteBuffer parameter instead of allocating new buffers
    scratch buffers are borrowed and returned in the method

tie/Bundle.properties
  add messages:
    warning: no buffer pool with big enough buffers
    info: buffer pools initialized
    error: wrong size buffer returned to pool
    warning: failed check guard (writing past allocated space)

clusterj-tie/pom.xml.in
  added sun.misc to import packages for Cleaner internal class

FixedByteBufferPoolImpl.java
  implement a pool of fixed size buffers for NdbRecord and Utility buffer
  each buffer in the pool is the same size
  the pool grows without bound as more buffers are needed
  optionally a guard can be allocated immediately after the data
    in the buffer and checked when the buffer is returned to guarantee
    that the buffer was not overwritten by errant code

VariableByteBufferPoolImpl.java
  implement variable size buffer pool for Blob read and write
  the sizes are specified in configuration property
    com.mysql.clusterj.byte.buffer.pool.sizes
  if this property is set to “1” no buffer pooling occurs
  if no pool has a big enough buffer size, a single use buffer is obtained
    and immediately after use, it is “cleaned” by calling the unsupported
    method “clean” on the object in the buffer’s “cleaner” field.