Bug#34638573 Compile MySQL with clang 15
Additional patch for MacOS

The most recent clang version reports`;
ddl0impl.h:127:3: error:
definition of implicit copy assignment operator for 'Row' is deprecated
because it has a user-declared destructor [-Werror,-Wdeprecated-copy-with-dtor]

Change-Id: I7707fc7a0364ad89ae5156c269fd4cd3d0daa992
(cherry picked from commit a549a700662199e76876871cf1eb1062d8daa92f)