Bug#34670950 ndb.ndb_stop_on_error generates core files even if test succeed for debug build Bug#33574176 Compile MySQL with GCC 12
Problem#1:

ndb.ndb_stop_on_error test was added when fixing Bug #24945638
STOPONERROR = 0 WITH UNCONTROLLED EXIT RESTARTS IN SAME WAY AS PREVIOUS
RESTART.

When testing a SIGSEGV signal was used to trigger uncontrolled node
crashes, if data node was a debug build the default behavior is to
generate core file on SIGSEGV signal.

Normally when injecting crashes we use CRASH_INSERTION macro but that has
some sideffects that would hide the intended test of fix.

Fix#1:

Explicitly turn off core file dumps before raising the SIGSEGV signal.

Problem#2:

Building with error injection support caused compile warning with GNU
compiler 12.2.

storage/ndb/src/kernel/blocks/cmvmi/Cmvmi.cpp: In member function 'Cmvmi::execNDB_TAMPER(Signal*)':
storage/ndb/src/kernel/blocks/cmvmi/Cmvmi.cpp:229:11: error: array subscript 0 is outside array bounds of 'int[0:]' [-Werror=array-bounds]
  229 |     printf("%u", *invalid_ptr); // SEGV
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~

Fix#2:

Use raise(SIGSEGV) instead, having a filled in signal information is
not relevant.

Change-Id: Ib5a2db265d2e3ba4e75ca78b634e4b4aacb4bf1c