Post Push Fix: Resolving Valgrind errors on WL branch
  Description:
    Error: Conditional jump or move depends on uninitialised value(s)

  Fix:
    The constructor for Ignorable_event is called from Rows_query_log_event.