WL#7069: Provide data dictionary information in serialized form
Post-push fix: Fix Clang build warning:
unittest/gunit/dd_sdi-t.cc:54:17: error: using namespace
      directive in global context in header [-Werror,-Wheader-hygiene]
using namespace dd;

When merging unit tests, unit test .cc files are interpreted
as headers since they are #included. Remove 'using namespace'
and explicitly mention the namespace where needed instead.