Bug #31870392 ADD DEPENDENCY ON LIBPROTOBUF-LITE
WL #13459: Optimize hash table in hash join
added sql/immutable_string.h which uses protobuf utililty functions for
encoding/decoding variable size integers.
This creates an explicit dependency on the protobuf runtime library.

If we configure with -DWITH_MYSQLX=0, the build may fail with:

sql/immutable_string.h:248: error:
undefined reference to 'google::protobuf::io::CodedOutputStream::WriteVarint64ToArray(unsigned long, unsigned char*)'

The fix is to add en explicit dependency on libprotobuf-lite.

Also: if we use "bundled" protobuf, do
  INCLUDE_DIRECTORIES(BEFORE SYSTEM ${BUNDLED_PROTO_SRCDIR})
to ensure that we do not include any headers from system protobuf (if installed).

Change-Id: Iff5984eec4051e1bb9405d3a2b85da228670a894
(cherry picked from commit ba18646d2e1082c3e0136626a81d0821ca5a0c16)