Bug#36716069 Compile MySQL with GCC 15 [noclose]
This patch fixes warnings for RelWithDebInfo build.
Default build, except -DWITH_NDBCLUSTER_STORAGE_ENGINE=0

acl_table_user.cc:2052:12:
bits/move.h:221:11: error: *(std::remove_reference<int&>::type*)this is used uninitialized [-Werror=uninitialized]

sql_planner.cc:1108:68:
error: array subscript 64 is above array bounds of uint [64] {aka unsigned int [64]} [-Werror=array-bounds=]

hypergraph_optimizer-t.cc:7658:62:
error: array subscript -1 is outside array bounds of void [] [-Werror=array-bounds=]
 7658 |   size_t count(NodeMap map) const { return m_num_subplans[map]; }

hypergraph_optimizer-t.cc:7631:72: note: at offset -8 into object of
size [0, 9223372036854775807]
allocated by operator new []
 7631 |       : m_graph(graph), m_num_subplans(new size_t[1llu << num_relations]) {

log_event.cc:970:30: error:
((mysql::binlog::event::Log_event_header*)((char*)this + 16))[7].
mysql::binlog::event::Log_event_header::unmasked_server_idis used uninitialized [-Werror=uninitialized]
  970 |   server_id = common_header->unmasked_server_id & opt_server_id_mask;

mysql_client_test.cc:492:51: error:
%s directive output may be truncated writing up to 4086 bytes into a region of size between 9 and 4095 [-Werror=format-truncation=]

Change-Id: Ibfe733340aaa8ca15008559fa0f6ef54a54314fc
(cherry picked from commit 7627a84502a8f22723e0ff5f2eab3e9b34540036)