Bug#28728485 "RESTART" ALWAYS TIMESOUT IN NDB_MGMD WHEN NDBD IS NOT STARTED
PROBLEM STATEMENT:
Executing "RESTART" command in ndb_mgm when the data nodes were in not started
state always resulted in a time out error:

ndb_mgm> ALL STOP
ndb_mgm> ALL RESTART
Connected to Management Server at: localhost:1186
Executing RESTART on all nodes.
Starting shutdown. This may take a while. Please wait...
Restart failed.
*  2003: Restart failed
*        5025-Time-out due to node shutdown not completing in time: Temporary
error: Timeout expired

DESCRIPTION:
Bug #11757421 introduced new logic for "RESTART". After this patch, when
RESTART was called, ndb_mgm sends a signal to stop all the data nodes and
waited for the data nodes to change its nodestate to stopped. However,
since the data nodes were not in not started state, ndb_mgm finds no alive
data nodes to send the stop signal. So, no signal is sent and data nodes
never come to stopped state. This causes the command to timeout as shown
above.

FIX:
Skip waiting when there are no alive data nodes to send stop signal to.

Change-Id: I1b2e671e3442b8b7ec100b629572ee055abb27a3