WL#12974 Frontend for MySQL Router's keyring
Post-Push fix.

Build fails with -Werror and -D_FORTIFY_SOURCE=1 due to

  error: ignoring return value of 'char* getcwd(char*, size_t)', declared
  with attribute warn_unused_result [-Werror=unused-result]

RB: 22481