WL#14259 Post push fix. unused-result warning in ndb_password.cpp.
storage/ndb/src/common/portlib/ndb_password.cpp:113:10:
error: ignoring return value of 'ssize_t write(int, const void*, size_t)',
       declared with attribute warn_unused_result [-Werror=unused-result]
  113 |     write(fd_out, prompt, strlen(prompt));
      |     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: I11b067e3fbd2f68b4682f5451bfd701ae724bba5