BUG#30519928 INTERMEDIATE MASTER WITH SEMISYNC SHOWS HIGH CPU USAGE DUE TO MUTEX SPINNING
Post-push fix for 5.7: unbreak the build on macOS
sql/locks/shared_spin_lock.cc:242:3: error: no matching
      function for call to 'my_atomic_store64'
  my_atomic_store64(&this->m_exclusive_owner, self);

Change-Id: I374d9893d0c37d58ef5786e1ccad34b5c85d1383