Bug#29623286 NDB : NO LOGGING OF API DETECTED HEARTBEAT ISSUES
Post push fix.

Problem:
ndbmtd failed to build on ubuntu (PB2) due to ODR violation

error: type 'struct ThreadData' violates the C++ One Definition
Rule [-Werror=odr]
../common/logger/./storage/ndb/src/common/logger/BufferedLogHandler.cpp:31:8: note: a different type is defined in another translation unit

Solution:
In BufferedLogHandler.cpp wrap struct ThreadData in an anonymous local
namespace.

Change-Id: I60f9f35d78b901fa63c07c4bcbbe6f02a731c691