WL#8726
 - compiler error detected with -Werror=logical-op which points
   out that condition in the assert which intends to quickly
   detect that a parse error code is not returned is faulty.
 - this has been wrong ever since it was implemented
 - fix by changing the condition to an AND.

  sql/ndb_local_connection.cc:85: error: logical 'or' of collectively
     exhaustive tests is always true [-Werror=logical-op]
     assert(last_errno != ER_PARSE_ERROR ||
                                         ^