Bug#34754817 Reconsider message "Failed to set ODirect errno:" as it is repeated
Follow up patch. Build breakage on OpenSUSE15 and Ubuntu 20.04 when
compiling with GCC 9.

AsyncFile.cpp:1172:52: error: use of deleted function 'AsyncFile::odirect_set_log_state::odirect_set_log_state()'
 1172 |     AsyncFile::odirect_set_log_bp[FsOpenReq::BP_MAX];
      |                                                    ^
In file included from AsyncFile.cpp:32:
AsyncFile.hpp:161:10: note: 'AsyncFile::odirect_set_log_state::odirect_set_log_state()' is implicitly deleted because the default definition would be ill-formed:
  161 |   struct odirect_set_log_state {
      |          ^~~~~~~~~~~~~~~~~~~~~
AsyncFile.hpp:161:10: error: use of deleted function 'std::atomic<_Tp>::atomic() [with _Tp = NDB_TICKS]'
In file included from AsyncFile.hpp:29,
                 from AsyncFile.cpp:32:
/usr/include/c++/9/atomic:198:7: note: 'std::atomic<_Tp>::atomic() noexcept [with _Tp = NDB_TICKS]' is implicitly deleted because its exception-specification does not match the implicit exception-specification ''
  198 |       atomic() noexcept = default;
      |       ^~~~~~

Change-Id: I111c041825f193dec145bec00dd6428c554e6785
(cherry picked from commit 5e99e2ddd92874fcba6b6bcd8f4ddc6254baa1d9)