WL#8726
 - compiler error detected with -Werror=literal-suffix since
   there need to be space between literal and identifier.

  storage/ndb/test/ndbapi/testScanFilter.cpp:747: error: invalid
    suffix on literal; C++11 requires a space between literal
    and identifier [-Werror=literal-suffix]
     ERR_EXIT(dict, "Can't get table"TABLE_NAME);
                    ^

 - fix by adding space between literal and identifier
 - similar to VS2015 "breaking changes"

(cherry picked from commit 4d82208212452fa7a603a6dba135888bba3f8beb)