Bug#30537830 TESTDICT -N CREATETABLEWHENDBISFULL T6 - NOT TESTABLE SINCE WL#9835/7.6.2
    Reviewed-by: Mikael Ronström <mikael.ronstrom@oracle.com>

    Description
    ===========

    The test "testDict -n CreateTableWhenDbIsFull T6" is not guaranteed to
    succeed since 7.6.2 and WL#9835 "Poolification for data memory".

    When creating a table one 8KB page is always allocated by DBACC for the
    primary key hash index.

    The former IndexMemory used by DBACC is since WL#9835now integrated with
    DataMemory.

    That is when Db is full there will be no free IndexMemory 32K pages.

    Since DBACC keep four 8KB pages on each 32KB data memory page, there can
    still be some 8KB pages free for DBACC, but that could also be that there are
    no free 8KB page.

    That is, creating a table when db is full, may or may not succeed.

    In 7.5 and earlier where IndexMemory was a separate memory resource it was
    unlikely that both DataMemory and IndexMemory got full at the same time and
    test was very unlikely to fail.

    How To Repeat
    =============

    Run test: testDict -n CreateTableWhenDbIsFull T6

    In rare occasions one can get:

    random seed: 3641534532
    testDict started [2019-11-10 23:06:16]
    |- T6
    - CreateTableWhenDbIsFull started [2019-11-10 23:06:16]
    ERROR: 827 Out of memory in Ndb Kernel, table data (increase DataMemory)
               Status: Permanent error, Classification: Insufficient space
               File:
    /export/home/tmp/ws/hudson-autotest-build-itch-at-446/mysql/storage/ndb/test/s
    rc/HugoTransactions.cpp (Line: 952)
    |- TRANSACTION
    Error0: 625: Out of memory in Ndb Kernel, hash index part (increase
    DataMemory)
    TRANSACTION was not created when DB is full
      |- runCreateTableWhenDbIsFull FAILED [2019-11-10 23:09:18]
    - CreateTableWhenDbIsFull FAILED [2019-11-10 23:09:18]

    Solution
    ========

    Allow create table to fail with "Error0: 625: Out of memory in Ndb Kernel,
    hash index part (increase DataMemory)".

    If creation succeed inserting a row should fail as before.

    Both kind of failures count as successful behaviour of test.