Bug#34278103 Compile MySQL with GCC 13 [noclose]
For a Debug build, with -O2, we get:

In file included from /usr/include/string.h:548,
 from extra/googletest/googletest-release-1.12.0/googletest/include/gtest/xxxxxx/gtest-port.h:262,
 from extra/googletest/googletest-release-1.12.0/googletest/include/gtest/gtest-message.h:55,
 from extra/googletest/googletest-release-1.12.0/googletest/include/gtest/gtest-assertion-result.h:46,
 from extra/googletest/googletest-release-1.12.0/googletest/include/gtest/gtest.h:59,
 from unittest/gunit/item_json_func-t.cc:23:
In function void* memset(void*, int, size_t),
    inlined from void TRASH(void*, size_t) at include/memory_debugging.h:72:9,
    inlined from static void Item::operator delete(void*, size_t) at sql/item.h:962:10,
    inlined from void item_json_func_unittest::BM_JsonSearch(size_t) at unittest/gunit/item_json_func-t.cc:721:78:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:59:33:
error: <anonymous> may be used uninitialized [-Werror=maybe-uninitialized]
   59 |   return __builtin___memset_chk (__dest, __ch, __len,
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
   60 |                                  __glibc_objsize0 (__dest));
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
unittest/gunit/item_json_func-t.cc: In function void item_json_func_unittest::BM_JsonSearch(size_t):
unittest/gunit/item_json_func-t.cc:721:78: note: <anonymous> was declared here
  721 |   auto search = new Item_func_json_search(table.in_use, new Item_field(&field),
      |                                                                              ^

gcc somehow thinks we may call this:
  static void operator delete(void *ptr [[maybe_unused]],
                              size_t size [[maybe_unused]]) {
    TRASH(ptr, size);
  }

The fix is to evaluate 'new Item_field(&field)' separately.

Change-Id: I5d73561f900043092bcd982fffc8462707627f1a
(cherry picked from commit e536c8a446b97ac9c90ce957ba1c34547b798993)