Bug#27802681 ADD SUPPORT FOR NATIVE GCC ON SOLARIS
Patch for trunk.

In the past we have been using misc gcc compilers on Solaris. These
compilers are no longer able to build the server, so we switched to
Oracle Studio. There is now a port of gcc 7 available as a native
compiler in Solaris, both for Intel and Sparc.

Remove obsolete/wrong cmake code for gcc on Solaris, use:
  /usr/bin/g++ --version
  g++ (GCC) 7.3.0
which has proper library support on Solaris 11.4

================
cmake/os/SunOS.cmake

Raise minimum compiler version for both gcc and Studio.

Remove obsolete cmake code for supporting non-native gcc compilers.

================
/mysys_ssl/CMakeLists.txt

Suppress -Wdeprecated-declarations for MD5 functions.

================
sql/sys_vars.cc
sql/sys_vars.h:138:0: error: "DEPRECATED" redefined [-Werror]
define DEPRECATED(X) X

/usr/include/openssl/ssl.h:2356:0:
note: this is the location of the previous definition
define DEPRECATED __attribute__((deprecated))

Change-Id: I6596d37466b4a1d031a506eb099e655aff14ff2c