Bug#18620520 CORRECT TYPO IN ER 1755(ER_MTS_CANT_PARALLEL)
Problem
------ 
TYPO in ER 1755.
Show Slave Status:
................
................
                   Last_Errno: 1755
                   Last_Error: Cannot execute the current event group in the
parallel mode. Encountered event Gtid, relay-log name
./slave-relay-bin.000002, position 363 which prevents execution of this event
group in parallel mode. Reason: The master does not support the selected
parallelization mode. It may be too old, or replication was started from an
event internal to a transaaction..

Fix
------
Change in:
File: log_event.cc
Line number: 2894
Line: "to a transaaction.");