BUG#24961893 - GROUP REPLICATION BREAKS BUILD ON SPARC32
Description:
-----------
Building current MySQL 5.7 and trunk on sparc 32 breaks:

In file included from /usr/include/procfs.h:23:0,
                 from
.../mysql/rapid/plugin/group_replication/libmysqlgcs/src/bindings/xc
om/xcom/task.c:58:
/usr/include/sys/procfs.h:42:2: error: #error "Cannot use procfs in the large
file compilation environment"
 #error "Cannot use procfs in the large file compilation environment"

  ^
*** Error code 1

How To Repeat:
-------------
Use a solaris machines.

Set up environment:
export PATH=/opt/gcc/bin:/opt/csw/bin:$PATH

git clone git@myrepo:mysql
cd mysql
git checkout mysql-5.7

export CC=/opt/gcc/bin/gcc
export CXX=CXX=/opt/gcc/bin/g++

export WITH_BOOST=/usr/local/share

mkdir build && cd build

/opt/csw/bin/cmake .. -DWITH_EMBEDDED_SERVER=OFF -DCMAKE_C_FLAGS="-m32"
-DCMAKE_CXX_FLAGS="-m32"

gmake -j80

Fix:
-------------
Removed unused header in XCom code in GR.