Bug#36716069 Compile MySQL with GCC 15 [noclose]
storage/ndb/tools/NdbImportUtil.cpp:1335:23: error:
allocation of insufficient size '0' for type uchar
{aka unsigned char} with size 1 [-Werror=alloc-size]

Remove obsolete check for gcc 4.7 (we currently require at least gcc 10)

Change-Id: Iae774d3a45ed08a101e8dd64b97d3bf7293c0271
(cherry picked from commit 61707927f183ab790648a5014594cda9f19c2074)