Bug#32200253 bootstrap fails if hostname is not set
Post-push fix: broken build on macOS:
router/src/harness/src/socket_operations.cc:54:53:
error: unused function 'endpoint_to_name' [-Werror,-Wunused-function]

Change-Id: I6fad07010d764f722bb317b7f3713cc6b83db1f5
(cherry picked from commit c0fd5e8aede18837abee6a044588cfe703b84796)