WL#15649 Expose Router configuration in metadata
Post-push fix: broken build with clang on Windows:
error: definition of implicit copy constructor for
'SectionConfigExposer' is deprecated because it has a
user-declared destructor [-Werror,-Wdeprecated-copy-with-dtor]
  virtual ~SectionConfigExposer() = default;

note: due to 'SectionConfigExposer' being dllexported
Change-Id: I8190376b22538cb3bef47bbc6ad1ffda37d3a46b
(cherry picked from commit 2f89061aa342b5a711ca598a4b7ecab8bea582c6)