Post-push Fix
Error: 'old_pre_checksum_fd' was not being defined if build without debug,

Fix: Moved the assert statment inside the #if loop so that it doesnt get called
     if the build is without debug.