Bug #34531492 Build heatwave on aarch64
Add cmake variable LINUX_ARM

Use LINUX_ARM variable to disable intel-specific compiler flags.

Fix misc low-level get_cycles() functions, with appropriate assembler
for aarch64.

Always build the 'qxtpg' tool, rather than relying on the executable
pre-built for intel. Disable the keyword 'register' generated by Flex.
Note that this requires the 'flex' package to be installed.

rpdoprst_init.c:
error: incompatible type for argument 6 of log
expected va_list but argument is of type void *

Missing from this patch: A replacement for intrinsics:
fatal error: immintrin.h: No such file or directory

Change-Id: I5e577689a1702404054b98c09f3e3b2f74f2ea43