1. Fixing build errors on Solaris
 Issue:
 Error: The function "memcpy" must have a prototype.

 Fix:
  Included the header file string.h

2. Updated the comments in sql/log_event.h to reflect the change in the name of
   the library