MDEV-6131 Unable to build Connector/ODBC 5.2.5 undefined reference to `my_charset_latin1'
Add charsets to the client API
(they are declared with MYSQL_PLUGIN_IMPORT, meaning the intention is to have them public)