Bug#30188095 MISSING INCLUDE IO.H IN DUK_MODULE_SHIM.C
Problem
=======

Building clang on windows:

    router/src/mock_server/src/duk_module_shim.c(271,7): warning:
    implicit declaration of function 'write' is invalid in C99
    [-Wimplicit-function-declaration]
      if (write(STDERR_FILENO, buf, buf_len) < 0) {
          ^

Change
======

include io.h on windows

RB: 22840