Bug#33424843 Sign-compare build error with with GCC 11 on Ubuntu 21.10
Problem:
--------

Attempting to build with GCC 11 caused the following build error:

NdbThread.cpp:359:25: error: comparison of integer expressions
of different signedness: 'NDB_THREAD_STACKSIZE' {aka 'long unsigned
int'} and 'long int' [-Werror=sign-compare]
359 |   if (thread_stack_size < PTHREAD_STACK_MIN)

The error is due to a change in glibc 2.34 where PTHREAD_STACK_MIN
is no longer constant when _DYNAMIC_STACK_SIZE_SOURCE or
_GNU_SOURCE are defined.

Fix:
----

- Return an error if PTHREAD_STACK_MIN is -1 which indicates an
  error. Add a cast to the comparison to take care of the compiler
  error.
- Minor refactoring of the function involving moving some code to
  avoid unnecessary malloc + free in failure scenarios, the use of
  [[maybe_unused]], moving variable declarations closer to their
  initial usage, and const correctness.

Change-Id: I9f1bbd7799cb5f48a1a6f1ee00f905764bff09e9