Bug#36292498: Compile MySQL with clang 18 [noclose]
Building with libc++ 18 fails because operator+() and operator-() in
mem_root_deque's iterator don't have the const qualifier.

/usr/lib/llvm-18/bin/../include/c++/v1/__algorithm/sort.h:320:52: error: invalid operands to binary expression ('const mem_root_deque<std::string>::Iterator<std::string>' and 'difference_type' (aka 'long'))
  320 |   const _RandomAccessIterator __leftmost = __first - difference_type(1);
      |                                            ~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~

Change-Id: Idefbe23d7c51de6778a3779a3f36b65b7ac0c37a
(cherry picked from commit 3352b43912a037db5643a1b008329ef190337b05)