Bug#35015376 pymysql: caching sha2: Unknown packet for public key
Using pymysql, connecting fails:

  import pymysql

  connection = pymysql.connect(
    host='127.0.0.1', port=6446,
    user='caching2', password='pass')
  pymysql.err.OperationalError: caching sha2:
  Unknown packet for public key: b'-'

pymsyql opens an unencrypted connection which asks for a public-key.
That public-key is sent as is (whence the '-' which is the start of the
public-key), but it should be prefixed 0x01.

Change
------

- Wrap the public-key in a server-side AuthMethodData packet, instead of
  the client-side AuthMethodData (which isn't prefixed with 0x01).

Change-Id: I280c143daae620c83c61dfa9e3824610fc8f4150